name: basicpipeline
on: 
 push:
   branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: show files
          run: ls
        - name: step1
          run: echo "hello"
        - name: step2
          run: echo " Display pipeline"
        - name: conditional step
          if: success()
          run: echo "Pipeline is successful"
        - name: Build the code
          run: echo "Building the code"
        - name: test the code
          run: echo "Testing"
        - name: Deploy the code
          run: echo "Deploying the code"
        - name: Create build file
          run: echo "This is my app build" > build.txt
        - name: Create deploy build
          run: mkdir deploy
        - name: Move file to deploy folder
          run: mv build.txt deploy/
        
        
