name: CICD
on: 
 push:
   branches: ["main"]
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
         - name: Create build file
           run: echo "This is my app build" > build.txt
         - name: Upload artifact
           uses: actions/upload-artifact@v4
           with:
             name: my-artifact
             path: build.txt
   deploy:
       needs: build
       runs-on: ubuntu-latest
       steps:
         - name: download artifact
           uses: actions/download-artifact@v4
           with:
             name: my-artifact
         - name: Show file
           run: cat build.txt
      
    
